### ISSUE TITLE
2.2.0 prerelease-4，在多显示器下使用时，从大显示器到小显示器（缩放150%）时，资源管理器的列表项目发生重叠的情况

### ISSUE THREAD

**Issue by peter-fan-cn** [kingToolbox/WindTerm#256]
当前版本  2.2.0 prerelease-4, 操作系统 win10 专业版 21H1

![image](https://user-images.githubusercontent.com/42033907/141034203-f160de98-653a-4406-a7a6-5d23ad3ff2eb.png)
看图，我是笔记本连接外部显示器。笔记本自身的屏幕为全高清屏（1920*1080），按150%缩放显示，连接外部显示器为24寸显示器（1920*1080），以外部显示器为主屏幕。当软件从外部显示器拖动到笔记本显示器时，发生了如图的情况。

**Comment by 107295472** [comment]
能不能用英文?尊重一下

**Comment by kingToolbox** [comment]
I have fixed this in the past two days. But since I don't have a test environment, I am not sure if this has been completely fixed. Especially `Qt 5.12.4`'s support for high DPI is not good enough. 

I will upgrade `Qt 5.12.4` to `Qt 6.2.2` next month, the new version provides better high DPI support. At that time, let's see if this bug still needs to be fixed. I will update the progress here, please stay tuned, thank you.

**Comment by kingToolbox** [comment]
The new [WindTerm_2.2.0_Prerelease_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) version has been released, and this issue may have been solved, please download and check it, thank you.

BTW:
If it has not been completely resolved, please wait for the upgraded version next month. I believe that this issue should be completely resolved by then.

**Comment by peter-fan-cn** [comment]
The issue is solved  

> The new [WindTerm_2.2.0_Prerelease_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) version has been released, and this issue may have been solved, please download and check it, thank you.
> 
> BTW: If it has not been completely resolved, please wait for the upgraded version next month. I believe that this issue should be completely resolved by then.

**Comment by peter-fan-cn** [comment]
start application in the outside screen (1920x1080)   display, look at the line spacing.
![image](https://user-images.githubusercontent.com/42033907/141891857-0d7c9594-9dc0-4b0d-a018-478871ef42ed.png)

then move it to the built in screen (1920x1080) zoon in 150%
![image](https://user-images.githubusercontent.com/42033907/141892014-189ffcf8-cb73-49cb-abea-6575a8fd90fe.png)

and If open new shells
![image](https://user-images.githubusercontent.com/42033907/141892087-c0fbce77-8e1b-410d-aae1-784ff77670be.png)

move back to the outside screen, then you can see that the line spacing has become larger.

![image](https://user-images.githubusercontent.com/42033907/141892135-f18079e0-6691-482f-9677-90f5f52b11ab.png)

**Comment by kingToolbox** [comment]
Thank you for providing so many intuitive screenshots, so that I have been very clear about the problem. `Filer`, `Session` and `Outline` are all self-painted components, but `Explorer` is a standard `Qt Widget`. This is why only `Explorer` has this problem. 

As I said, I will wait until next month to upgrade to the `Qt 6.2.2` to solve this problem. In addition, I will also consider the reason you mentioned that it may not be repainted in time. Any progress will be updated here. Please stay tuned.

**Comment by peter-fan-cn** [comment]
v2.2.2. issue still there. @kingToolbox

**Comment by peter-fan-cn** [comment]
Perfect resolved

**Comment by hisune** [comment]
> Sorry for the late reply. I just returned from vacation.
> 
> The new [Windterm_2.3.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.3-prerelease) version has been released, and this issue have been solved, please download and check it, thank you. If there are still bugs, please let me know, thank you.

Some icons in version 2.3.0 display problems. My main screen is 3200*1800, and the secondary screen is 1920*1080. The icon cannot be displayed normally in the secondary screen, and the icon is too large.

![优效截图20220210092725](https://user-images.githubusercontent.com/7941669/153319421-4e3db799-024f-4b9b-9610-0b8d75186802.png)

**Comment by kingToolbox** [comment]
@hisune
Sorry for the late reply. Because I've been sick recently.

I will investigate this issue and fix it. And I will update here if there is any progress. Please stay tuned, thank you.

**Comment by kingToolbox** [comment]
@hisune 
I am happy to inform you that [WindTerm_2.3.1](https://github.com/kingToolbox/WindTerm/releases/tag/2.3.0) has been released and this issue has been fixed. Please download and check it. If there are still bugs, please let me know, thank you.

**Comment by hisune** [comment]
@kingToolbox 

Thank you for your fix, I tried the latest version and this problem has been improved, which is great! But there is still a small problem, as follows：
When opening the software, some icons still appear too large：
![微信图片_20220223104246](https://user-images.githubusercontent.com/7941669/155253843-c56c32d3-5da0-4c14-8027-bc833b95690c.png)

But when I move the mouse to a larger icon, it will become a normal size, or I click the mouse outside the software, and all the larger pictures will return to normal.：
![微信图片_20220223104253](https://user-images.githubusercontent.com/7941669/155253855-980e2333-8223-4f3d-be3c-71ff975992bc.png)

Another similar problem is that when I put the mouse on the normally displayed icon, it will become larger (but not all icons will be like this)：
![微信截图_20220223104657](https://user-images.githubusercontent.com/7941669/155253865-dbe00213-c100-48eb-be64-2c2e9df73138.png)

All in all, the problem has been improved. It would be great if it could be made more perfect. Thank you for your attention to this issue.

> @hisune I am happy to inform you that [WindTerm_2.3.1](https://github.com/kingToolbox/WindTerm/releases/tag/2.3.0) has been released and this issue has been fixed. Please download and check it. If there are still bugs, please let me know, thank you.

**Comment by kingToolbox** [comment]
Sorry, my test wasn't careful enough. I will continue to fix these bugs and update here with any progress, and thank you very much for your well-illustrated description, which has helped me a lot.

**Comment by MrRen-sdhm** [comment]
This issue still exists in the latest version(2.6.0) @kingToolbox.
https://github.com/kingToolbox/WindTerm/releases/tag/2.6.0
